const express = require('express');
const nodemailer = require('nodemailer');

const router = express.Router();

// =================================================
// Gmail Transporter
// =================================================

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,
  secure: false,

  // Force IPv4 connection
  family: 4,

  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },

  // Connection timeout settings
  connectionTimeout: 15000,
  greetingTimeout: 15000,
  socketTimeout: 20000,
});

// =================================================
// Verify Gmail Connection
// =================================================

transporter.verify((error, success) => {
  if (error) {
    console.error('❌ Gmail transporter error:', error);
  } else {
    console.log('✅ Gmail transporter is ready');
  }
});


// =================================================
// Send Medical Report
// =================================================

router.post('/send', async (req, res) => {

  try {

    const {
      email,
      patientName,
      patientId,
      date,
      condition,
      confidence,
      probabilities,
    } = req.body;


    // -------------------------------------------------
    // Validate email
    // -------------------------------------------------

    if (!email) {

      return res.status(400).json({
        success: false,
        message: 'Recipient email is required',
      });

    }


    // -------------------------------------------------
    // Email Content
    // -------------------------------------------------

    const emailHTML = `

      <div style="
        font-family: Arial, sans-serif;
        max-width: 600px;
        margin: auto;
        padding: 20px;
        background-color: #f1f5f9;
      ">

        <div style="
          background-color: white;
          padding: 25px;
          border-radius: 15px;
        ">

          <h2 style="
            color: #0f172a;
            text-align: center;
          ">
            EYE HEALTH SCREENING REPORT
          </h2>

          <hr>

          <p>
            <strong>Patient Name:</strong>
            ${patientName || 'John Doe'}
          </p>

          <p>
            <strong>Patient ID:</strong>
            ${patientId || 'P123456'}
          </p>

          <p>
            <strong>Date:</strong>
            ${date || ''}
          </p>

          <p>
            <strong>Condition:</strong>
            ${condition || 'No diagnosis'}
          </p>

          <p>
            <strong>Confidence:</strong>
            ${confidence || '0%'}
          </p>


          <h3 style="color: #334155;">
            Prediction Probabilities
          </h3>


          <table style="
            width: 100%;
            border-collapse: collapse;
          ">

            <tr>
              <td style="padding: 8px;">
                Cataract
              </td>

              <td style="
                padding: 8px;
                text-align: right;
              ">
                ${probabilities?.Cataract ?? 0}%
              </td>
            </tr>


            <tr>
              <td style="padding: 8px;">
                Conjunctivitis
              </td>

              <td style="
                padding: 8px;
                text-align: right;
              ">
                ${probabilities?.Conjunctivitis ?? 0}%
              </td>
            </tr>


            <tr>
              <td style="padding: 8px;">
                Healthy
              </td>

              <td style="
                padding: 8px;
                text-align: right;
              ">
                ${probabilities?.Healthy ?? 0}%
              </td>
            </tr>

          </table>


          <hr>

          <p style="
            color: #64748b;
            font-size: 13px;
            text-align: center;
          ">
            This report was generated by the Eye Healthcare System.
          </p>

        </div>

      </div>

    `;


    // =================================================
    // Send Email
    // =================================================

    console.log('📧 Sending medical report to:', email);

    await transporter.sendMail({

      from: `"Eye Healthcare System" <${process.env.EMAIL_USER}>`,

      to: email,

      subject: 'Eye Health Screening Report',

      html: emailHTML,

    });


    console.log('✅ Medical report email sent successfully');


    // =================================================
    // Success Response
    // =================================================

    return res.status(200).json({

      success: true,

      message: 'Medical report sent successfully',

    });


  } catch (error) {

    console.error('❌ Email sending error:', error);


    return res.status(500).json({

      success: false,

      message: 'Failed to send medical report',

      error: error.message,

    });

  }

});


module.exports = router;