const express = require('express');
const axios = require('axios');

const router = express.Router();

// =================================================
// Brevo API
// =================================================

const BREVO_API_URL = 'https://api.brevo.com/v3/smtp/email';


// =================================================
// Send Medical Report
// =================================================

router.post('/send', async (req, res) => {

  try {

    const {
      email,
      patientName,
      patientId,
      date,
      condition,
      confidence,
      probabilities,
    } = req.body;


    // -------------------------------------------------
    // Validate recipient email
    // -------------------------------------------------

    if (!email) {

      return res.status(400).json({
        success: false,
        message: 'Recipient email is required',
      });

    }


    // -------------------------------------------------
    // Check Brevo API Key
    // -------------------------------------------------

    if (!process.env.BREVO_API_KEY) {

      console.error('❌ BREVO_API_KEY is not configured');

      return res.status(500).json({
        success: false,
        message: 'Brevo API key is not configured',
      });

    }


    // -------------------------------------------------
    // Check Sender Email
    // -------------------------------------------------

    if (!process.env.EMAIL_USER) {

      console.error('❌ EMAIL_USER is not configured');

      return res.status(500).json({
        success: false,
        message: 'Sender email is not configured',
      });

    }


    // -------------------------------------------------
    // Email Content
    // -------------------------------------------------

    const emailHTML = `

      <div style="
        font-family: Arial, sans-serif;
        max-width: 600px;
        margin: auto;
        padding: 20px;
        background-color: #f1f5f9;
      ">

        <div style="
          background-color: white;
          padding: 25px;
          border-radius: 15px;
        ">

          <h2 style="
            color: #0f172a;
            text-align: center;
          ">
            EYE HEALTH SCREENING REPORT
          </h2>

          <hr>

          <p>
            <strong>Patient Name:</strong>
            ${patientName || 'John Doe'}
          </p>

          <p>
            <strong>Patient ID:</strong>
            ${patientId || 'P123456'}
          </p>

          <p>
            <strong>Date:</strong>
            ${date || ''}
          </p>

          <p>
            <strong>Condition:</strong>
            ${condition || 'No diagnosis'}
          </p>

          <p>
            <strong>Confidence:</strong>
            ${confidence || '0%'}
          </p>


          <h3 style="color: #334155;">
            Prediction Probabilities
          </h3>


          <table style="
            width: 100%;
            border-collapse: collapse;
          ">

            <tr>
              <td style="padding: 8px;">
                Cataract
              </td>

              <td style="
                padding: 8px;
                text-align: right;
              ">
                ${probabilities?.Cataract ?? 0}%
              </td>
            </tr>


            <tr>
              <td style="padding: 8px;">
                Conjunctivitis
              </td>

              <td style="
                padding: 8px;
                text-align: right;
              ">
                ${probabilities?.Conjunctivitis ?? 0}%
              </td>
            </tr>


            <tr>
              <td style="padding: 8px;">
                Healthy
              </td>

              <td style="
                padding: 8px;
                text-align: right;
              ">
                ${probabilities?.Healthy ?? 0}%
              </td>
            </tr>

          </table>


          <hr>

          <p style="
            color: #64748b;
            font-size: 13px;
            text-align: center;
          ">
            This report was generated by the Eye Healthcare System.
          </p>

        </div>

      </div>

    `;


    // =================================================
    // Send Email through Brevo HTTPS API
    // =================================================

    console.log('📧 Sending medical report through Brevo...');
    console.log('📨 Recipient:', email);


    const response = await axios.post(
      BREVO_API_URL,

      {
        sender: {
          name: 'Eye Healthcare System',
          email: process.env.EMAIL_USER,
        },

        to: [
          {
            email: email,
            name: patientName || 'Patient',
          },
        ],

        subject: 'Eye Health Screening Report',

        htmlContent: emailHTML,
      },

      {
        headers: {
          accept: 'application/json',
          'api-key': process.env.BREVO_API_KEY,
          'content-type': 'application/json',
        },

        timeout: 30000,
      }
    );


    // =================================================
    // Success
    // =================================================

    console.log('✅ Medical report email sent successfully');

    console.log('📨 Brevo message ID:', response.data?.messageId);


    return res.status(200).json({

      success: true,

      message: 'Medical report sent successfully',

      messageId: response.data?.messageId,

    });


  } catch (error) {

    console.error('❌ Brevo email sending error');


    if (error.response) {

      console.error(
        'Brevo status:',
        error.response.status
      );

      console.error(
        'Brevo response:',
        error.response.data
      );

    } else {

      console.error(
        'Error:',
        error.message
      );

    }


    return res.status(
      error.response?.status >= 400 &&
      error.response?.status < 500
        ? error.response.status
        : 500
    ).json({

      success: false,

      message: 'Failed to send medical report',

      error:
        error.response?.data ||
        error.message,

    });

  }

});


module.exports = router;